import requests
import base64
import time
import re
from typing import Dict, Any, Optional
from pydantic import BaseModel

class DeployResult(BaseModel):
    success: bool
    pr_url: str
    branch_name: str
    pr_title: str
    pr_body: str
    preview_url: str
    message: str

def parse_github_url(repo_url: str):
    """Parse 'https://github.com/owner/repo' into (owner, repo)."""
    # Remove trailing .git or slashes
    repo_url = repo_url.rstrip("/").removesuffix(".git")
    parts = repo_url.split("/")
    if len(parts) >= 2:
        return parts[-2], parts[-1]
    raise ValueError("Invalid GitHub URL format")

def build_pr_body(diagnosis: Dict[str, Any], fix_result: Dict[str, Any]) -> str:
    """Generate a detailed markdown PR body."""
    patched_files = fix_result.get("patched_files", [])
    files_list = "\n".join([f"- `{pf['file_path']}`" for pf in patched_files])
    confidence = fix_result.get("confidence", "unknown")
    
    body = f"""## Root Cause
{diagnosis.get('root_cause', 'Unknown root cause.')}

## Why It Happened
{diagnosis.get('why_it_happened', 'No additional details provided.')}

## Fix Applied
The following files were modified to fix the issue:
{files_list}

## Verification
✅ Sandbox Execution: **Verified** (The patched code runs successfully in an isolated environment).

## Confidence
**{confidence.title()}** confidence in this fix.

---
*Generated by Submit & Heal 🩺*
"""
    return body

async def create_pr(repo_url: str, fix_result: Dict[str, Any], diagnosis: Dict[str, Any], github_token: str) -> DeployResult:
    """Create a PR on GitHub with the verified fix."""
    try:
        owner, repo = parse_github_url(repo_url)
    except Exception:
        return DeployResult(
            success=False, pr_url="", branch_name="", pr_title="", pr_body="", preview_url="",
            message="Invalid GitHub URL provided."
        )

    headers = {
        "Authorization": f"token {github_token}",
        "Accept": "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28"
    }
    
    base_api_url = f"https://api.github.com/repos/{owner}/{repo}"

    # 1. Get default branch and its SHA
    try:
        # Fetch repo info to get default branch
        repo_resp = requests.get(base_api_url, headers=headers)
        if repo_resp.status_code == 401:
            return DeployResult(
                success=False, pr_url="", branch_name="", pr_title="", pr_body="", preview_url="",
                message="Invalid or expired GitHub token."
            )
        elif repo_resp.status_code == 404:
            return DeployResult(
                success=False, pr_url="", branch_name="", pr_title="", pr_body="", preview_url="",
                message=f"Repository not found or token lacks access (make sure token has 'repo' scope)."
            )
        repo_resp.raise_for_status()
        
        default_branch = repo_resp.json().get("default_branch", "main")
        
        # Get SHA of default branch
        ref_resp = requests.get(f"{base_api_url}/git/ref/heads/{default_branch}", headers=headers)
        ref_resp.raise_for_status()
        base_sha = ref_resp.json()["object"]["sha"]
        
    except Exception as e:
        return DeployResult(
            success=False, pr_url="", branch_name="", pr_title="", pr_body="", preview_url="",
            message=f"Failed to access repository: {str(e)}"
        )

    # 2. Create new branch
    timestamp = int(time.time())
    branch_name = f"fix/auto-heal-{timestamp}"
    
    try:
        create_ref_resp = requests.post(
            f"{base_api_url}/git/refs",
            headers=headers,
            json={"ref": f"refs/heads/{branch_name}", "sha": base_sha}
        )
        create_ref_resp.raise_for_status()
    except Exception as e:
        return DeployResult(
            success=False, pr_url="", branch_name="", pr_title="", pr_body="", preview_url="",
            message=f"Failed to create branch on GitHub: {str(e)}"
        )

    # 3. Update files on the new branch
    for file_info in fix_result.get("patched_files", []):
        file_path = file_info["file_path"]
        patched_content = file_info["patched_content"]
        
        try:
            # Get current file SHA
            file_resp = requests.get(f"{base_api_url}/contents/{file_path}", headers=headers, params={"ref": branch_name})
            
            if file_resp.status_code == 200:
                file_sha = file_resp.json()["sha"]
            else:
                # File might not exist? Or some other error
                file_sha = None

            # Base64 encode the new content
            encoded_content = base64.b64encode(patched_content.encode('utf-8')).decode('utf-8')
            
            put_data = {
                "message": f"fix: auto-heal patch for {file_path}",
                "content": encoded_content,
                "branch": branch_name
            }
            if file_sha:
                put_data["sha"] = file_sha
                
            update_resp = requests.put(
                f"{base_api_url}/contents/{file_path}",
                headers=headers,
                json=put_data
            )
            update_resp.raise_for_status()
            
        except Exception as e:
            return DeployResult(
                success=False, pr_url="", branch_name="", pr_title="", pr_body="", preview_url="",
                message=f"Failed to push patched file '{file_path}' to GitHub: {str(e)}"
            )

    # 4. Create Pull Request
    # Truncate title cleanly
    raw_title = diagnosis.get('root_cause', 'Auto-heal fix')
    if len(raw_title) > 55:
        pr_title = f"🩺 Auto-heal: {raw_title[:55]}..."
    else:
        pr_title = f"🩺 Auto-heal: {raw_title}"

    pr_body = build_pr_body(diagnosis, fix_result)

    try:
        pr_resp = requests.post(
            f"{base_api_url}/pulls",
            headers=headers,
            json={
                "title": pr_title,
                "body": pr_body,
                "head": branch_name,
                "base": default_branch
            }
        )
        pr_resp.raise_for_status()
        pr_data = pr_resp.json()
        pr_url = pr_data.get("html_url", "")
        
    except Exception as e:
        return DeployResult(
            success=False, pr_url="", branch_name="", pr_title="", pr_body="", preview_url="",
            message=f"Failed to open Pull Request: {str(e)}"
        )

    return DeployResult(
        success=True,
        pr_url=pr_url,
        branch_name=branch_name,
        pr_title=pr_title,
        pr_body=pr_body,
        preview_url="",  # Vercel preview URL placeholder
        message="Pull Request successfully created."
    )
